---
# tasks file for minions
- name: install k3s
  shell: |
    wget https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf && \
    chmod +x k3s-armhf && \
    sudo mv k3s-armhf /usr/local/bin/k3s

- name: put startup script
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
  vars:
    target: "{{ https_master }}"
    token: "{{ k3s_token }}"

# TODO reboot
