---
- name: install k3s
  shell: |
    wget https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf && \
    chmod +x k3s-armhf && \
    sudo mv k3s-armhf /usr/local/bin/k3s

- name: put startup script
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755

# TODO reboot
